### PR TITLE
added check plus in phone body

### PR DESCRIPTION
**Pull request by akhll**

### CODE REVIEW

**Comment by titarenko** [comment]
`var fixRuPhoneBase = fixPhoneBuilder(10, 12, 'ru');
function fixRuPhone () {
replace +8 in the beginning with 8; 
run fixRuPhoneBase
}
`

**Review by titarenko — CHANGES_REQUESTED** [review]
var fixRuPhoneBase = fixPhoneBuilder(10, 12, 'ru'); function fixRuPhone () { replace +8 in the beginning with 8; run fixRuPhoneBase }

**Comment by akhll** [comment]
Non actual

**Comment by akhll** [comment]
Non actual

**Pull request closed without merging**
